# Generated by Django 4.2 on 2024-05-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_item_item_desc_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
